### ISSUE TITLE
OffsetPaginatedCollection example schema

### ISSUE THREAD

**Issue by jpraet** [belgif/openapi-common#11]
A standard OffsetPaginatedCollection schema (with properties self, next, prev, first, last, pageSize, page) could potentially be defined for implementing the https://www.belgif.be/specification/rest/api-guide/#pagination guidelines.

However, given that the guidelines only impose the naming of these pagination related properties, and not whether they should be used, this may not be easy to standardize on Belgif level?

**Comment by pvdbosch** [comment]
The many optional fields are indeed the reason why there's no standard schema.
Especially the `last` and `total` properties might not be easy to provide by an API depending on its internals.

If they'd be in a standard schema, even if not listed as required, clients would expect them to be filled in.

**Comment by aethy** [comment]
Maybe it might be helpful to add an example schema in the REST guide, from which people can copy-paste and tailor to their needs? It needs of course to be clear that it's not to be copy-pasted as such, but the easier you make it, the more chance it will be correct and not something completely different

**Comment by JDMKSZ** [comment]
Maybe it might be helpful to add an example schema in the REST guide, from which people can copy-paste and tailor to their needs? It needs of course to be clear that it's not to be copy-pasted as such, but the easier you make it, the more chance it will be correct and not something completely different

**Comment by pvdbosch** [comment]
@jpraet is working on a type for CBSS, we could include this as example schema in the guide when ready (after WG review)

**Comment by jpraet** [comment]
```yaml
    OffsetPaginationCollection:
      type: object
      description: Base type for collection resources using offset-based pagination.
      externalDocs:
        url: https://www.belgif.be/specification/rest/api-guide/#pagination
      properties:
        pageSize:
          description: Maximum number of items per page.
          type: integer
          format: int32
          minimum: 1
        page:
          description: Index of the current page of items (1-based).
          type: integer
          format: int32
          minimum: 1
        total:
          description: >
            Total number of items acrross all pages.
            If query parameters are used to filter the result set, this is the total of the collection result set, not of the entire collection.
          type: integer
          format: int64
          minimum: 0
        first:
          description: Hyperlink to the first page.
          type: string
          format: uri
        prev:
          description: Hyperlink to the previous page.
          type: string
          format: uri
        last:
          description: Hyperlink to the last page.
          type: string
          format: uri
        next:
          description: Hyperlink to the next page.
          type: string
          format: uri
      required:
        - pageSize
        - page
        - total
        - first
        - last
      example:
        pageSize: 20
        page: 5
        total: 195
        first: "https://api.ksz-bcss.fgov.be/demo/v1/pets?pageSize=20&page=1"
        prev: "https://api.ksz-bcss.fgov.be/demo/v1/pets?pageSize=20&page=4"
        last: "https://api.ksz-bcss.fgov.be/demo/v1/pets?pageSize=20&page=10"
        next: "https://api.ksz-bcss.fgov.be/demo/v1/pets?pageSize=20&page=6"
```
