### ISSUE TITLE
Add additionalProperties to HttpLink, LocalizedString, ea

### ISSUE THREAD

**Issue by wsalembi** [belgif/openapi-common#7]
Following https://github.com/belgif/rest-guide/issues/110 and the decision to not accept unknown properties, some objects in openapi-commons must be changed to mark them explicitly extensible

* HttpLink: to add other fields next to href
* LocalizedString: to add other languages
* e.a ??

**Comment by pvdbosch** [comment]
I don't think it is needed:

*HttpLink*

It is usually only used in the response, not in requests (and the rule only applies to requests).
Also, APIs usually use HttpLink in combination with an allOf, so the other properties are known, e.g.

```YAML
PersonReference:
    allOf:
      - "$ref": "./common/v1/common-v1.yaml#/definitions/HttpLink"
      - type: object
        properties:
          ssin:
            "$ref": "#/definitions/Ssin"
```

*LocalizedString*

If a Belgian API deviates from the three declared languages (nl, fr, de), it usually declares its own variant type to be explicit about which languages are provided.  E.g. if the server supports "nl", "fr" and "en", using the LocalizedString from openapi-common would lead the client to believe that "de" would be processed by the server but it would be silently ignored, and that "en" isn't supported.

Such a type can still evolve in a backwards-compatible manner. E.g. removal of a language is covered:

> In specific situations, where a (known) input parameter is not needed anymore and can be safely ignored:
> * either it can stay in the API definition with a deprecation flag and a "not used anymore" description
> * or it can be removed from the API definition as long as the server ignores this specific parameter.
